name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run tests
        run: xcodebuild clean test -workspace "Example/SeededCrypto.xcworkspace" -scheme 'SeededCrypto-Example' -destination 'platform=iOS Simulator,name=iPhone 11'
     
